[features]
seeds = false
skip-lint = false

[programs.localnet]
simple_nft = "4jvMtVYUSyWoVvaxwAnWzSNdqaZHJArKG3zyFQGZjuty"

[programs.devnet]
simple_nft = "4jvMtVYUSyWoVvaxwAnWzSNdqaZHJArKG3zyFQGZjuty"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/iml1111/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
