[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "6HVPBXc7DJfdkMrYWeKwx5RKnMiyEn4Tg3zdei97EKN5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/iml1111/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
